//
// Generated file, do not edit! Created by nedtool 5.2 from token.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __TOKEN_M_H
#define __TOKEN_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>token.msg:1</tt> by nedtool.
 * <pre>
 * message Token
 * {
 *     simtime_t creationTime;
 *     double size;
 * }
 * </pre>
 */
class Token : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::simtime_t creationTime;
    double size;

  private:
    void copy(const Token& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Token&);

  public:
    Token(const char *name=nullptr, short kind=0);
    Token(const Token& other);
    virtual ~Token();
    Token& operator=(const Token& other);
    virtual Token *dup() const override {return new Token(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(::omnetpp::simtime_t creationTime);
    virtual double getSize() const;
    virtual void setSize(double size);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Token& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Token& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TOKEN_M_H

